### PR TITLE
Add support of RetroWave OPL3 hardware protocol

### PR DESCRIPTION
**Pull request by ReimuNotMoe**
Add support of RetroWave OPL3 hardware protocol.

### CODE REVIEW

**Comment by ReimuNotMoe** [comment]
Resolves #190

**Comment by Wohlstand** [comment]
I'll review this once I get my home, on a first look, seems good. One note:
We don't use "Egyptian" brackets, so, please follow the code style of project:
```cpp
if(condition)
{
    some();
}
```

**Comment by ReimuNotMoe** [comment]
> I'll review this once I get my home, on a first look, seems good. One note: We don't use "Egyptian" brackets, so, please follow the code style of project:
> 
> ```c++
> if(condition)
> {
>     some();
> }
> ```

The coding style is changed.

**Review by Wohlstand — APPROVED** [review]
Looks fine to me. I think I'll tweak some other style cases by myself. I'll merge this.

**Comment by Wohlstand** [comment]
Sorry for the late reply, I was very tired and slept for a long time.

**Comment by ReimuNotMoe** [comment]
You're welcome. Take care.

**Pull request merged**
