### PR TITLE
load null instrument in generator to prevent crash

### LINKED ISSUE #46: Playing keyboard without instrument loaded may crash
Just load the software with no instrument and press a piano key. (either keyboard or midi)
Invalid access found by the address sanitizer.

In NoteManager it has out-of-bounds on first access of the channel array, because size is 0. 
`if(channels[chan].note == -1)`

### PR DESCRIPTION
**Pull request by jpcima**
fixes #46

### CODE REVIEW

**Comment by Wohlstand** [comment]
I have made something another in parallel, but your is much simpler here.
seems, that needed to be combined, as my solution means "touch nothing" while in your case it will still send commands to the chip

default

**Comment by Wohlstand** [comment]
But... instead of that variable I probably can just check the count of channels allocated in the voice manager thing, but this is more understandible

**Comment by jpcima** [comment]
If any solution can prevent NULL problems from triggering in software, I'll take this one.

**Comment by Wohlstand** [comment]
Just now I send the combining thing, and also, there is `FmBank::emptyInst()` that generates an instrument entry with default parameters.

**Pull request merged**
