### PR TITLE
dro: fix the 4op detection

### PR DESCRIPTION
**Pull request by jpcima**
Fix a case of badly checked 4op register.

### CODE REVIEW

**Comment by jpcima** [comment]
Also @Wohlstand, I found a strange thing.

When I create a new bank in SBTimbre, the instrument has Con=1 and Fb=6.
Capturing a single note, the importer founds Con=0 and Fb=0.

On examination of the commands, the sequence showed this on the channel.
```
[CH00] C0: 3D   // set Con=1 Fb=6
[CH00] C0: 30   // set Con=0 Fb=0 (?)
[CH00] B0: 31   // key-on
[CH00] B0: 11   // key-off
```

I don't understand why the C0 register has a reset in the middle.

**Comment by Wohlstand** [comment]
Can you attach the SBI / IBK file that contains that instrument? It's very possible a bug that need to fix...

**Comment by jpcima** [comment]
Remade in DOSBox-X, and included in archive:
- SBI instrument ; it's the default
- DRO capture of single note
- capture of screen from SBTimbre ; matching SBI in bank editor,
  but same error from DRO import: Fb and Alg having both 0

[sbtimbre-sample.tar.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2741604/sbtimbre-sample.tar.gz)

sbtimbre

**Comment by Wohlstand** [comment]
Maybe that means a bug of SB Timbre itself? Try to make same instrument in OPL3BE and compare the sounding

**Comment by jpcima** [comment]
Have 3 recordings.
1. one is from DRO import in BE, which is wrong because of Fb/Alg like I said above.
2. one is SBTimbre recorded from DOSBox.
3. one is from BE playback and SBI saved from SBTimbre; it shows same Fb/Alg as SBTimbre.

SBI 2 and 3 sound almost same but I can hear a little difference.
DRO is completely wrong as you'll be able to hear.

[capture.tar.gz](https://github.com/Wohlstand/OPL3BankEditor/files/2742791/capture.tar.gz)

**Pull request merged**
