### PR TITLE
fix a misspelling of instrument: distortion guitar

### PR DESCRIPTION
**Pull request by jpcima**
This mistake is in all the projects, and genadldata, so I have to also fix it in all others..

### CODE REVIEW

**Comment by jpcima** [comment]
In fact I'm not sure if this should be edited in libADLMIDI, because maybe the name was edited purposefully to keep it under the 16 character limit for a display reason.

**Comment by Wohlstand** [comment]
in ADLMIDI instrument names are never using, there are only using in comments inside of generating `adldata.cpp` file. So, as now I have disable comments by default to have more compact file, then everything must be fine :wink:

**Comment by Wohlstand** [comment]
But yeah, that typo possibly made by Joel originally as I wasn't edited that list

**Comment by jpcima** [comment]
How to fit unicode curses code to a library which does not have it?
Translate the unicode to cp437 by conversion table. Hooray for crappy hacks :smile: 
There is no opportunity for russian this time, so I give you my apology.

https://github.com/jpcima/adljack/blob/traduction/sources/i18n.cc

**Comment by Wohlstand** [comment]
> How to fit unicode curses code to a library which does not have it?
Translate the unicode to cp437 by conversion table. Hooray for crappy hacks smile
There is no opportunity for russian this time, so I give you my apology.

It's okay as 8bit charsets are never allowed to have mixing of languages. Russian Cyrillic is CP866 that is used in DOS and still in Windows's console (jerks from M$, why you still use different char-set in a console! Let's use UTF8 like BASH does!)

**Comment by jpcima** [comment]
I have not told you the full truth and it's not really MS at fault really.
It's because ANSI PDCurses uses a cp437 bitmap font, and Unicode forces to use TTF rendering for full range. But I find this TTF rendering to look awful and I want to just stay on the bitmap. :smile:

**Comment by Wohlstand** [comment]
I wanted to merge this now, but I have tired while review as I came to home very late... So, It's a big chance I'll merge the stuff tomorrow with giving of the complete Russian translation from my side :wink:

**Pull request merged**
