### PR TITLE
complete realtime audio support

### PR DESCRIPTION
**Pull request by jpcima**
#19 

:warning: HUGE UPDATE. please test extensively :warning: 

Redesign of audio code in order to meet pro-audio standards.
I enable the audio to be processed at low latency with complete lock freedom.
As bonus, I add all platforms that RtAudio supports. (RtAudio is a widely used library in open source music-oriented software)
(ALSA and QtMM code removed, I have no will or interest to port this)

I set a default latency of 20ms, but lower are achievable. For that, the editor could have a setting which allows to control it in GUI. (but would take a program restart to consider)
There is a change about the sample rate, now the sample rate of the soundcard is taken.

In RtAudio, more platforms can be added with -D flags, but for now I have just put the basic ones.
For example if I add ASIO for windows, the lowest possible latencies can be met. But this will likely not be compatible with Win9x, so I have not added it.

I cannot test Win9x and hardware chip, but here's how it's supposed to work in the new model:
it will use the same audio thread to do the realtime work, but it will send the zero signal into the sound card. A small overhead will be added, but on the other hand it benefits of the much better MIDI latency.
This overhead is probably not much, but if you want to eliminate, it's doable by implementing a dummy audio driver. (RtAudio has a dummy driver but that will not work, because it never invokes the callback)

For detail on how the things are put together: there are three threads which cooperate.
- UI thread sends control by FIFO ringbuffer
- MIDI thread sends events by FIFO ringbuffer, but drops event if full buffer (no blocking)
- Audio thread processes events from both ringbuffers and manages chip

Hopefully there are no mallocs in the RT path which I have missed.

### CODE REVIEW

**Comment by Wohlstand** [comment]
I'll tweak around the whole thing to check it out... Looks nice :fox_face:
About of 9x, I have the plan to make the fake emulator that will appear on 9x build and will send data to real chip, and clean up generator in a whole which I gonna to do.  Then will be possible to use emulator on win9x too! The only problem was inability to play sound due no QtMultimedia in qt4 and a Phonon shit that not buildable on 9x.

**Comment by jpcima** [comment]
Yeah the core of this code to check out is in files generator_realtime.{h,cpp}.

I have made a separation of the 3 thread APIs in functions of their own distinct prefix, to make it understandable clearly.
`ctl_*` stuff is GUI, `midi_*` is MIDI, and `rt_*` is realtime audio

For the implement method I replaced the old push-pull API model into a completely callback driven model. 

The Appveyor build of 9x has given me a lot of trouble. Your Mingw environment does not include the directsound header (but it has libdsound.lib). I added dsound in the source tree and it's crap, it would be best if you modified Mingw on your server side to include it.

**Comment by jpcima** [comment]
Had any chance at trying this on Windows 9x yet?
I've managed to create a 98 VM in Virtualbox, but not yet to manage a Samba setup to be able to communicate files with it..

**Comment by Wohlstand** [comment]
Oh, sees my email wasn't posted here...
I told that on Win98 I use legacy WinSCP 4.3.6 to access my host via SSH/SFTP, or I downloading my AppVeyor builds through installed IE http://wohlsoft.ru/docs/_laboratory/_Builds/win32/

**Comment by jpcima** [comment]
| I told that on Win98 I use legacy WinSCP 4.3.6 to access my host via SSH/SFTP

This works thanks.

I uploaded a modified MinGW for inclusion of the dsound header in it. https://ufile.io/289cd
(never mind this header says "the Wine project" in it, it is really from recent MinGW)
You can put this on server for AppVeyor to use?

MD5
385f9b4d581e0b1951f3010b6ae046b9  MinGW-6-3-x86-dw2+dsound.zip
6520901a420c3de33a00e9b22fd85c6d  MinGW-6-3-x86-dw2.zip

**Comment by Wohlstand** [comment]
Did you took my MinGW 6.3 from the url that referred in AppVeyor's config? I built Qt 4.4.3 that I also fixed it myself to build it on MinGW 6.3. 

It's better to make the check of `dsound.h` existence that will say is need to include custom or use system.

The one thing that for regular builds I using system MinGW that was provided by AppVeyor where the stuff is that was as-is.

**Comment by Wohlstand** [comment]
As this needs some review and extra check out, and small rework on generator side, I'll also pull this and will work on this...

**Comment by Wohlstand** [comment]
One thing why I disabled focus from the list of instruments: that totally annoys me when I testing chords by keyboard instead playing notes, it just jumps far-far away into different instrument, that very annoying... So, let's implement the flag to turn on/off this focusing as for me it's needed to disable focus to easily play chords by just keyboard as myself I have no MIDI keyboard to test notes and at same time jump different instruments by mouse

**Comment by jpcima** [comment]
> One thing why I disabled focus from the list of instruments

Can there just be a key event filter which keeps the arrow keys. Just the arrow keys, page up and down too. The letter keys can do whatever they want.

**Comment by Wohlstand** [comment]
> Can there just be a key event filter which keeps the arrow keys. Just the arrow keys, page up and down too. The letter keys can do whatever they want.

Yes, that a good idea! :smile:  As arrows are not used to play notes, only to navigate...

**Comment by jpcima** [comment]
Ok revert as you please and later I can do this if you want.

**Comment by Wohlstand** [comment]
> Ok revert as you please and later I can do this if you want.

Anyway, your focus enabling I wasn't reverted and the stuff now as-is, but yeah, I'll turn off the focus in the form and will push now

**Pull request merged**
