### PR TITLE
Very low latency part 1/2

### PR DESCRIPTION
**Pull request by jpcima**
This patch allows to define the latency in GUI and save it in settings.

It seems I have been in file conflicts because we have edited the same menus!
I see you have been busy on Win9x work!

### CODE REVIEW

**Comment by Wohlstand** [comment]
Yeah, and current state unfortunately broken... It won't start on my Win98 machine with VC++ error "abnormal program termination" and I ran my Win7 machine where is environment with Qt 4 I built to try debug the stuff... To just don't wait while AppVeyor will build a whole thing...

**Comment by jpcima** [comment]
It has something to do with my commits?

**Comment by Wohlstand** [comment]
I think I mistook in something while moved code: my OPL proxy does dynamic loading of DLL that built via WattCom and that dll does direct access to OPL3 chip. I made some different thing that manages Library and LoadLibrary stuff, and it's possibly I mistook here

**Comment by jpcima** [comment]
I don't think I will be of any help on this. Good luck
I'll continue on with low latency part 2

**Comment by Wohlstand** [comment]
Oh, one thing, I figured out to run GDB 5.2 on my 9x machine, and it says "Desired latency 0.02" and "Buffer size 0". Why zero buffer?

**Comment by jpcima** [comment]
Uh oh, this looks bad! sample rate is 0 ???

**Comment by Wohlstand** [comment]
And okay: it's really reasonable now to write a primitive screenshot tool that will work on Win9x, it's easy with Qt 4.4.3 I think...

But the gotten error is:
opl3-bank-crap

One thing: SAME assembly successfully ran on Win7

**Comment by jpcima** [comment]
You can change a thing real quick? Try this.

    `unsigned sampleRate = deviceInfo.preferredSampleRate;`

add
    `if (sampleRate == 0) sampleRate = 44100;`

**Comment by Wohlstand** [comment]
Gotta to fix...

**Comment by jpcima** [comment]
You're on real hardware or VM? DirectSound returning 0 sample rate seems impossible.
It VM, there may not necessarily be a sound device. So the fallback is on the Rtaudio dummy driver.

**Comment by Wohlstand** [comment]
I'm on real hardware. I want to check out the real chip behavior.

**Comment by Wohlstand** [comment]
The error is still be:
opl3-bank-crap

**Comment by jpcima** [comment]
You can merge #52 ?
It will answer if it's on dummy driver or not + print some debug.
If directSound is not probed right on this OS, it will be a thing to implement. Also a stupid thing, you have an updated directX?

**Comment by jpcima** [comment]
WAIT!!

**Comment by Wohlstand** [comment]
My machine had `Direct X 9.0c (4.09.0000.0904)`

**Comment by jpcima** [comment]
You can merge now. I have commited a mistake in my rush.

**Comment by Wohlstand** [comment]
Merged, now I'll build the stuff and run on my 9x machine again...

**Comment by jpcima** [comment]
Anyway I'm pretty sure at this point. I will work on making Win9x working, but on a reduced program.
I don't have yet the cross environment with Qt4.

**Comment by Wohlstand** [comment]
P.S. I think, you should allow user to run editor even with no audio device, even to just manage values, the user only will have no ability to listen the instruments, and it's will be jerky to force having the audio device...

**Comment by jpcima** [comment]
Yes you're right. I should code the fake driver absolutely.

**Comment by Wohlstand** [comment]
> Anyway I'm pretty sure at this point. I will work on making Win9x working, but on a reduced program.
I don't have yet the cross environment with Qt4.

One thing, I have patched that Qt4 build with custom QMake as stock was broken and incompatible with Qt Creator

**Comment by Wohlstand** [comment]
So, you can just copy mine Qt 4 into the same folder which referred in AppVeyor and also MinGW pack too, and just configure in Qt Creator (use latest Qt Creator), and in the properties add mine Qt4 by refering Qmake, add mine MinGW, and then make the toolchain that uses mine MinGW and my Qt4 build

**Comment by jpcima** [comment]
Seems I can have a sound driver in virtualbox! gotta find some sb16 drivers

**Comment by Wohlstand** [comment]
Yes, I always using SB16 driver in VirtualBox, but yeah, it doesn't simulates FM, [but I have to push the work](https://www.virtualbox.org/ticket/16914) made by @nukeykt to them, however, his patch is quite outdated: made in 2013 year and that successfully worked on WinXP, but with some small issues (quiting from MIDI player keeps FM sound playing. Probably a missing handling of reset request).

**Comment by Wohlstand** [comment]
I have tested your patch at me - the error is same, it still return me 0 sampleRate I had to override by 44100

**Comment by jpcima** [comment]
And he will agree to relicense the code in MIT to have the work accepted?

> I have tested your patch at me

Yes but I vaguely know the reason. You see, rtaudio will try in a fixed order all the available drivers, and pick the one that works. On win9x, directsound does not pass probing stage and it goes to fallback on dummy, hence samplerate 0. Directsound with samplerate 0 returned is impossible.

**Comment by Wohlstand** [comment]
> And he will agree to relicense the code in MIT to have the work accepted?

He have re-licensed his emulator into GPLv2 (on that moment it was GPLv3), so, there are will accent the thing. But, together with the emulator, is needed the patch to DevSB16.cpp to integrate the chip with existing sound card simulator.

I trying to catch something now:
```cpp
    try{
        audioOut->openStream(
            &streamParam, nullptr, RTAUDIO_SINT16, sampleRate, &bufferSize,
            &process, this, &streamOpts, &errorCallback);
    }
    catch ( RtAudioError &exception )
    {
        qDebug() << "RtAsio error (" << exception.getMessage().c_str() << ")!";
        return;
    }
    catch(...)
    {
        qDebug() << "Damn! It's not working!";
    }
```

**Comment by Wohlstand** [comment]
Okay, the exception wasn't caused and post-exception line worked... Seems the exception have came from another place...

**Comment by jpcima** [comment]
> I trying to catch something now

Normally the error callback which is set is already going to supersede throw.

> Okay, the exception wasn't caused and post-exception line worked... Seems the exception have came from another place...

Rtaudio with dummy is sure to pass the openStream stage. However it is not supposed to crash.
It is going to freeze the UI at one point, because it will wait on a ringbuffer to consume itself but never happens.

**Comment by Wohlstand** [comment]
Ha-ha, running on Win7 I found:
```
Object::connect: No such slot IRealtimeControl::changeNote(int)
Object::connect:  (sender name:   'noteToTest')
```

**Comment by Wohlstand** [comment]
```
Desired latency 0.02 
Buffer size 960 
Device was opened! 
Object::connect: No such slot IRealtimeControl::changeNote(int)
Object::connect:  (sender name:   'noteToTest')
QFileSystemWatcher: failed to add paths: E:\vitaly\_git_repos\libADLMIDI\fm_banks\op3_files
Using RtAudio API 8

MidiInWinMM::initialize: no MIDI input devices currently available.
```

**Comment by jpcima** [comment]
> MidiInWinMM::initialize: no MIDI input devices currently available.

Is it only a warning or fatal ?

**Comment by Wohlstand** [comment]
Warning, the app is works

**Comment by jpcima** [comment]
You know where to find the Virtualbox SB16 driver which works?

**Comment by jpcima** [comment]
Oh god, this sure promises fun times.
Time for me to "upgrade" to Qt4.

**Comment by Wohlstand** [comment]
I think, I know why audio not worked with Qt 4... some macro I have removed, but it was still used at you I have missed up...

**Comment by Wohlstand** [comment]
YAY, Qt4 build now works! :D

**Comment by jpcima** [comment]
?
What do you mean by "works"

**Comment by Wohlstand** [comment]
It plays sound on Win7 with both Qt4 and Qt5 now. For now I gotta to check 9x runtime again...

**Comment by Wohlstand** [comment]
Program is still erroring...

**Comment by jpcima** [comment]
Gdb gives you a backtrace?

**Comment by Wohlstand** [comment]
No, as error happens out of debug, and the program just exist...

**Comment by Wohlstand** [comment]
I trying to tweak around and puting various extra log prints...

**Comment by Wohlstand** [comment]
Aha!
The crap happen on Rt-Generator (stop happen when `Init Rt-Generator` happen)

default

**Comment by jpcima** [comment]
Ok what if this is used. Crash happens?

    `RtAudio *audioOut = new RtAudio(RtAudio::Api::RTAUDIO_DUMMY);`

**Comment by Wohlstand** [comment]
Gonna to try...

**Comment by jpcima** [comment]
generator_realtime.h : see WindowsMutex down there? try placing some debug in this.
Stuff works on NT for sure, but 9x no idea

**Comment by Wohlstand** [comment]
Just now I have made QMutex usage when targeting 9x, and... IT WORKS! :tada: :fox_face: :smile: 
There are working both emulator and real chip, however, while emulator working, DosBox seems fine, but when I ran Nuked, the lags of GUI are became, but toggling different emulator or real chip saves from lags

**Comment by jpcima** [comment]
Phew.. what good news I am glad to hear.
God damn.

**Comment by Wohlstand** [comment]
Just now pushed the stuff!

**Comment by jpcima** [comment]
Thank you!

**Comment by Wohlstand** [comment]
The CreateMutex was introduced with Windows XP: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682411(v=vs.85).aspx

**Comment by jpcima** [comment]
Right right. oh fuck I want to kill myself for screwing up this. Jesus christ

**Comment by jpcima** [comment]
WHY DOES IT COMPILE

**Comment by jpcima** [comment]
`#if _WIN32_WINNT >= 0x0600`

We should set a macro for low windows requirement to avoid this crap

**Comment by jpcima** [comment]
I'm adding, but to the CMake version only: Jack, WASAPI, ASIO (the low-latency drivers)
and Pulseaudio
and let's create a fake driver.

**Pull request merged**
