### PR TITLE
support new OPL proxy with dynamic address

### PR DESCRIPTION
**Pull request by jpcima**
#118 I implemented the new OPL proxy requested by @datajake1999 with port change UI.
I have no ability to test however, can you check that I did right?

### CODE REVIEW

**Comment by Wohlstand** [comment]
It must don't break the Win9x workflow, be sure the built DLL is still be runnable on Windows 98, otherwise, please keep my old OpenWatcom built DLL for compatibility reasons (for the case of modern deployment, the new DLL will be included).

**Comment by jpcima** [comment]
Never mind, I understood what you mean as I read into proxy code.

**Comment by jpcima** [comment]
I rearranged `opl_proxy` in a directory hierarchy which has both of `win9x` which is the old, and `modern` the new one as it has been posted.

**Comment by datajake1999** [comment]
[InpOut32Helper.zip](https://github.com/Wohlstand/OPL3BankEditor/files/2716767/InpOut32Helper.zip)
The directory with the modern source doesn't have the InpOut32Helper code.

**Comment by jpcima** [comment]
I fixed things and I made a build.
- Under the `modern` directory, DLL files were in confusion.
`liboplproxy.dll` was an old one, and `oplproxy.dll` was a new build made with MS C++ compiler.
I renamed `oplproxy.dll` to `liboplproxy.dll`, being the name that OPL3-BE searches for.
- MS symbol mangling being different, it needs to search without the '_' char at beginning.
- There was one more change to make such that loading would be permitted in Windows != 9x.

@datajake1999 do you have ability to confirm this build as working? the port setting is accessible in "Settings>Hardware OPL"
[opl3_bank_editor.zip](https://github.com/Wohlstand/OPL3BankEditor/files/2716778/opl3_bank_editor.zip)

**Comment by datajake1999** [comment]
The build you uploaded isn't screen reader accessible, and I think this is because it was built with an older QT version. The latest WIN32 release is screen reader accessible and I think this is because it uses a newer QT version which has accessibility features.
Can you please upload a build with the version of QT that is used for modern WIN32 builds?
Thanks.

**Comment by jpcima** [comment]
I would but I unfortunately this computer of mine doesn't have the toolchain set up for Qt5, so this is Qt4.
When the code is merged, Qt5 is going to be available by automatic builds.
I will let @Wohlstand validate the code for merging, because I don't have hardware for testing right now.

**Comment by jpcima** [comment]
Wait you may be in luck, I think Appveyor has artifacts avialable. https://ci.appveyor.com/api/buildjobs/l5sucg6by98gxb2t/artifacts/opl3-bank-editor%2Fopl3-bank-editor-dev-win32.zip

**Comment by datajake1999** [comment]
The address of my card is EF50, but when I enter the address it only enters EF5.

**Comment by jpcima** [comment]
Fixed it, it's just a dumb text input problem.
https://ci.appveyor.com/api/buildjobs/18ru39hrvts6dtup/artifacts/opl3-bank-editor%2Fopl3-bank-editor-dev-win32.zip

**Comment by datajake1999** [comment]
I just tested it with the correct port address and I don't get anything from the hardware. I don't know what I am doing wrong in my code, as the InpOut32Helper I am using is the same code I use in my OPL3 MIDI driver fork, which works perfectly.

**Comment by jpcima** [comment]
I completed the work and I fixed the bugs, this time tried on my side with a fake DLL. Does this look fine?
https://ci.appveyor.com/api/buildjobs/kjcm7gmmml454beo/artifacts/opl3-bank-editor%2Fopl3-bank-editor-dev-win32.zip

**Comment by datajake1999** [comment]
It still doesn't work. I compiled liboplproxy.dll with the _DEBUG define, and the debug log only shows the driver opening and closing, no reads or writes.

**Comment by jpcima** [comment]
@Wohlstand please debug on real card when you are able, if you don't mind.

**Comment by Wohlstand** [comment]
I know that some C-Media chips are lacks OPL3 chip on backend, but, I have some set of C-Media where it's is presented, so, will test on it...

**Comment by jpcima** [comment]
Ok instead of playing in WINE, I tested on real Windows following these steps.
1. open Windows XP in Virtualbox
2. took the latest of binary builds, replaced `liboplproxy.dll` with a _DEBUG build by mingw
3. created the folder `C:\OPLSynth`, destination of logging messages
4. I tick "Settings>Choose chip emulator>Proxy to real OPL3 chip"
5. I set the port in Hardware OPL
6. I select an instrument slot, play on keys a bit

The verdict: the `hwlog.txt` shows read and write commands to address range 0xef80-ef83.
My experience contradicts yours @datajake1999, I am able to see occurence of input/output.

**Comment by datajake1999** [comment]
I forgot to set the chip emulator to "Proxy to the real OPL3 chip". That was the problem. It works!

**Comment by Wohlstand** [comment]
I think, the usage of real OPL3 chip would be possible on Linux too: https://github.com/vgmrips/vgmplay/issues/39
After I'll test this, I'll try to run a test on my Linux host with same sound card...

**Comment by jpcima** [comment]
@Wohlstand for Linux, it can be made, have a look this code here.
https://github.com/aybe/dosbox-svn-daum/blob/bd7891dde34a20f00fd953921441f9cce8eb28ed/src/libs/porttalk/porttalk.cpp#L231-L248

It needs to require IO permissions from kernel, such that it can make privileged assembly calls from user space. The code needs the root and is probably 32 bit only.
Maybe, a separate service with setuid would do in this case.

**Comment by Wohlstand** [comment]
> It needs to require IO permissions from kernel, such that it can make privileged assembly calls from user space. The code needs the root and is probably 32 bit only.
Maybe, a separate service with setuid would do in this case.

I think, yeah, a proxy daemon or kernel module that will become as a bridge, that would be a solution. :fox_face:

**Comment by Wohlstand** [comment]
Done! :3

**Pull request merged**
