### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by jpcima**
This adds the just the translation. No dynamic switching, no change of UI.
However, I have fixed various english mistakes which I have found in the process.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Aha, you have a fail in Qt 4.4.3:
```
src/bank_editor.cpp: In member function 'void BankEditor::createLanguageChoices()':
src/bank_editor.cpp:1037:38: error: 'class QLocale' has no member named 'nativeLanguageName'; did you mean 'FijiLanguage'?
         QString name = QLocale(lang).nativeLanguageName();
                                      ^~~~~~~~~~~~~~~~~~
Makefile.Release:357: recipe for target '_build_data/_build_x32/opl3_bank_editor/_release/.obj/bank_editor.o' failed
```
So, please use `#if QT_VERSION >= 050000` to don't build unsupported things on Qt 4. But, to capture things from Windows 9x, you can use `_WIN32` and WinAPI that possibly allowed on 9x or keep English by default on platforms are don't support language detection

**Comment by jpcima** [comment]
I've added the little flag icons and changed this. Let's see if it fixes things..
Only issue, the language names will always be shown in english out of `QLocale`, and I have not found a fix. (except hardcoding)

**Comment by jpcima** [comment]
> you need to hook provide same lang-changed slot to Importer too as child dialogs usually don't auto-retranslating

You're right the importer dialog can receive a change of language while it's open.
In fact I have found somewhere that `changeEvent` is enough to detect a language change and I do not need to emit this signal.

Gotta play with PGE engine at some point, I have looked at what it was in video but haven't played it yet. It's curious to have mixed the FM music and the Nintendo game style; for me I was a Sega kid, I must have to do with being a FM-head now. :smile:

**Comment by Wohlstand** [comment]
> In fact I have found somewhere that changeEvent is enough to detect a language change and I do not need to emit this signal.

:+1: 

> Gotta play with PGE engine at some point, I have looked at what it was in video but haven't played it yet. It's curious to have mixed the FM music and the Nintendo game style; for me I was a Sega kid, I must have to do with being a FM-head now. smile

The episode that appeared on a videos: http://wohlsoft.ru/docs/Collected/Episodes/Lowsers%20Conquest%20Demo%20v%202.1%20(changed%20music).7z
A modded demo of Lowser's Conquest episode for legacy engine where I have replaced musics (are Nintendo-copyrighted) with random MIDI files I have in my huge collection. It's suggested to play the episode with "A2XT" config pack you can find in the "Documents" -> "Configuration packages" place :wink:

**Comment by jpcima** [comment]
I believe translation work is done now, if you want to check it.

> Anyway, I'm glad you have liked my big main project I working now

It's good :+1: got gameover at third level I believe because it's how much I suck at games at this point. :smile:
I don't play very much to be honest.
I didn't find how to use a gamepad, and I have used antimicro instead, I don't know if it's suppose to take native gamepad.

**Comment by Wohlstand** [comment]
Okay, just now I have pushed your branch into separated branch where I also have posted something from me you can pull and continue the work :wink:

**Comment by Wohlstand** [comment]
> I didn't find how to use a gamepad, and I have used antimicro instead, I don't know if it's suppose to take native gamepad.

Latest SDL2 supports gamepads well, and it's easy to use them, as engine allows you to configure any key/hat/axis to be mapped on a control key

**Comment by jpcima** [comment]
> I also have posted something from me you can pull and continue the work 

It's good in fact I consider to have completed all the items.
I have incorrectly accused dialog layout to have issues which turn out solved. (maybe the fact to "retranslate" has arranged the way it lays out in some way, I don't know. Works now)
It's just the piano widget which looks terrible and can use some rework.

**Comment by jpcima** [comment]
> Latest SDL2 supports gamepads well

I always had some particular experiences with SDL2 and gamepad.
I have bought one which is the cheapest thing on amazon, and it's not one of the "Xinput-compatibles". Nothing works with it natively.
So it needs the SDL2 program to accept `gamescontrollerdb.txt` files, and I have myself commited the definition of this gamepad to the community repo. https://github.com/gabomdq/SDL_GameControllerDB

**Comment by Wohlstand** [comment]
I have added the existence checking for "/../share/op3_bank_editor" path and I using "../src/translations" path instead. Just for a convenient debug. Anyway, it's better for me to add the proper install that I have made on PGE Project side in QMake. That was tricky, but it works. The reason why I using "build.sh" bash script - to make users less deal with kylotons of QMake's flags and automate sequence of actions to correctly deploy dependencies. With a case of CMake, I already automated everything inside of CMake script directly.

**Comment by Wohlstand** [comment]
I think, I'll merge the stuff now. But, before of that, I'll add the ability to save recently-selected language to restore it back on a next load.

**Comment by Wohlstand** [comment]
Everything is made! :fox_face: :+1:

**Comment by Wohlstand** [comment]
And yeah, I made support for native language names on Qt 4.8 and higher, but older Qt like 4.3 that is used for Win9x builds will use old code

**Comment by jpcima** [comment]
> before of that, I'll add the ability to save recently-selected language to restore it back on a next load.

Yeah definitely it's a must-have functionality.
(I'm in struggle with having a CI setup and deployment these last days, which is going to be complete soon I hope)

**Comment by Wohlstand** [comment]
P.S. Thanks for a hint for "nativeLanguageName()" function, Why I wasn't used it in PGE Editor before?

**Comment by jpcima** [comment]
I have in fact stopped using `nativeLanguageName` before you asked me, because default returned "American English" and that mismatched the UK flag used for "en" language.

**Comment by Wohlstand** [comment]
Then, you can make the condition to don't use `nativeLanguageName` when "en_US" is in use

**Pull request merged**
