### PR TITLE
fix a mistake of FIFO usage

### PR DESCRIPTION
**Pull request by jpcima**
It's another stupid thing for which you're going to scold me :grin: 
Caught a mistake which would corrupt FIFO when both ctl and midi would play.

By the way, I have tested ASIO on non-virtualized Windows. It's perfect.

### CODE REVIEW

**Comment by Wohlstand** [comment]
Glad that you have fixed that! :3

**Comment by Wohlstand** [comment]
One thing: on my WinXP VM the sound played poorly and with much longer latency (the VM itslef is very quick and plays sound perfectly even through my PGE MusPlay which uses SDL2 output with DirectSound backend)

**Comment by jpcima** [comment]
General purpose audio works OK in my VMs, but low latency audio is extremely poor.
VM testing is insignificant, test in a real machine.

**Comment by jpcima** [comment]
I'll add to that I know VirtualBox has some HUGE latency delays.
Hardly bearable for games, and utterly unusable for anything musical.

**Comment by Wohlstand** [comment]
Therefore is reasonable to run that stuff under Wine rather VM (however, a luck when some software will work or will crash or work glitchy)

**Comment by jpcima** [comment]
Definitely then look at this wine plugin called wineasio.

**Pull request merged**
